package com.dossier.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AiAnswerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiAnswerAllPropertiesEquals(AiAnswer expected, AiAnswer actual) {
        assertAiAnswerAutoGeneratedPropertiesEquals(expected, actual);
        assertAiAnswerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiAnswerAllUpdatablePropertiesEquals(AiAnswer expected, AiAnswer actual) {
        assertAiAnswerUpdatableFieldsEquals(expected, actual);
        assertAiAnswerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiAnswerAutoGeneratedPropertiesEquals(AiAnswer expected, AiAnswer actual) {
        assertThat(actual)
            .as("Verify AiAnswer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiAnswerUpdatableFieldsEquals(AiAnswer expected, AiAnswer actual) {
        assertThat(actual)
            .as("Verify AiAnswer relevant properties")
            .satisfies(a -> assertThat(a.getQuestionHash()).as("check questionHash").isEqualTo(expected.getQuestionHash()))
            .satisfies(a -> assertThat(a.getAnswer()).as("check answer").isEqualTo(expected.getAnswer()))
            .satisfies(a -> assertThat(a.getModel()).as("check model").isEqualTo(expected.getModel()))
            .satisfies(a -> assertThat(a.getTokens()).as("check tokens").isEqualTo(expected.getTokens()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiAnswerUpdatableRelationshipsEquals(AiAnswer expected, AiAnswer actual) {
        // empty method
    }
}
