package com.dossier.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBioAllPropertiesEquals(Bio expected, Bio actual) {
        assertBioAutoGeneratedPropertiesEquals(expected, actual);
        assertBioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBioAllUpdatablePropertiesEquals(Bio expected, Bio actual) {
        assertBioUpdatableFieldsEquals(expected, actual);
        assertBioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBioAutoGeneratedPropertiesEquals(Bio expected, Bio actual) {
        assertThat(actual)
            .as("Verify Bio auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBioUpdatableFieldsEquals(Bio expected, Bio actual) {
        assertThat(actual)
            .as("Verify Bio relevant properties")
            .satisfies(a -> assertThat(a.getPayload()).as("check payload").isEqualTo(expected.getPayload()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBioUpdatableRelationshipsEquals(Bio expected, Bio actual) {
        // empty method
    }
}
