package com.dossier.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FieldCacheAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldCacheAllPropertiesEquals(FieldCache expected, FieldCache actual) {
        assertFieldCacheAutoGeneratedPropertiesEquals(expected, actual);
        assertFieldCacheAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldCacheAllUpdatablePropertiesEquals(FieldCache expected, FieldCache actual) {
        assertFieldCacheUpdatableFieldsEquals(expected, actual);
        assertFieldCacheUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldCacheAutoGeneratedPropertiesEquals(FieldCache expected, FieldCache actual) {
        assertThat(actual)
            .as("Verify FieldCache auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldCacheUpdatableFieldsEquals(FieldCache expected, FieldCache actual) {
        assertThat(actual)
            .as("Verify FieldCache relevant properties")
            .satisfies(a -> assertThat(a.getFieldKey()).as("check fieldKey").isEqualTo(expected.getFieldKey()))
            .satisfies(a -> assertThat(a.getContextHash()).as("check contextHash").isEqualTo(expected.getContextHash()))
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getHitCount()).as("check hitCount").isEqualTo(expected.getHitCount()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldCacheUpdatableRelationshipsEquals(FieldCache expected, FieldCache actual) {
        // empty method
    }
}
