package com.dossier.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResumeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResumeAllPropertiesEquals(Resume expected, Resume actual) {
        assertResumeAutoGeneratedPropertiesEquals(expected, actual);
        assertResumeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResumeAllUpdatablePropertiesEquals(Resume expected, Resume actual) {
        assertResumeUpdatableFieldsEquals(expected, actual);
        assertResumeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResumeAutoGeneratedPropertiesEquals(Resume expected, Resume actual) {
        assertThat(actual)
            .as("Verify Resume auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResumeUpdatableFieldsEquals(Resume expected, Resume actual) {
        assertThat(actual)
            .as("Verify Resume relevant properties")
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getr2ObjectKey()).as("check r2ObjectKey").isEqualTo(expected.getr2ObjectKey()))
            .satisfies(a -> assertThat(a.getParsedJson()).as("check parsedJson").isEqualTo(expected.getParsedJson()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResumeUpdatableRelationshipsEquals(Resume expected, Resume actual) {
        // empty method
    }
}
