#!/usr/bin/env bash
# Build a fresh production .env from scratch.
# RUN ON: the NEW server, in the repo checkout. Use this when the old .env is unrecoverable.
#
#   ./05-bootstrap-env.sh
#
# Generates the values that can be generated (DB password, JWT secret, admin bcrypt hash) and
# prompts for the ones only you can supply (S3, SMTP, AI). Secrets are read with the terminal
# echo OFF and are never printed back or written to your shell history.
set -euo pipefail

ENV_FILE="${ENV_FILE:-.env}"

say()  { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m!!  %s\033[0m\n' "$*"; }
note() { printf '    \033[2m%s\033[0m\n' "$*"; }

[ -f docker-compose.prod.yml ] || { echo "Run from the repo checkout on the server." >&2; exit 1; }

if [ -e "$ENV_FILE" ]; then
  cp "$ENV_FILE" "$ENV_FILE.bak.$(date +%s)"
  warn "existing $ENV_FILE backed up — press Ctrl-C now if you did not mean to replace it"
  sleep 3
fi

# Docker Compose interpolates '$' inside .env values, so every '$' must be doubled. This is the
# documented footgun for the bcrypt hash, but it applies to ANY value — so escape them all.
# ('$$' collapses back to '$' on the way in, so this is lossless for values with no '$'.)
esc() { printf '%s' "$1" | sed 's/[$]/$$/g'; }

# Read a secret without echoing it, and without it landing in history.
ask_secret() { local __v; read -rs -p "    $1: " __v </dev/tty; echo >/dev/tty; printf '%s' "$__v"; }
ask_plain()  { local __v; read -r  -p "    $1: " __v </dev/tty;            printf '%s' "$__v"; }

say "Generating what can be generated"
MYSQL_ROOT_PASSWORD="$(openssl rand -base64 36 | tr -d '\n/+=' | cut -c1-32)"
JWT_BASE64_SECRET="$(openssl rand -base64 64 | tr -d '\n')"
note "MySQL root password: generated (32 chars)"
note "JWT signing secret:  generated (base64, 64 bytes)"
warn "A new JWT secret invalidates every existing session and extension token."

say "Admin account (created at API startup)"
note "Stored as a bcrypt hash — the plaintext never touches disk."
ADMIN_EMAIL="$(ask_plain 'Admin email (e.g. admin@kiwiply.com)')"
ADMIN_LOGIN="$(ask_plain 'Admin login  [admin]')"; ADMIN_LOGIN="${ADMIN_LOGIN:-admin}"
ADMIN_PW="$(ask_secret 'Admin password')"
ADMIN_PW2="$(ask_secret 'Admin password (again)')"
[ "$ADMIN_PW" = "$ADMIN_PW2" ] || { echo "Passwords do not match." >&2; exit 1; }
[ -n "$ADMIN_PW" ] || { echo "Empty password." >&2; exit 1; }
ADMIN_PASSWORD_HASH="$(docker run --rm httpd:2.4-alpine htpasswd -bnBC 10 "" "$ADMIN_PW" | tr -d ':\n')"
unset ADMIN_PW ADMIN_PW2
case "$ADMIN_PASSWORD_HASH" in
  '$2y$10$'*) note "bcrypt hash generated (${#ADMIN_PASSWORD_HASH} chars)" ;;
  *) echo "htpasswd did not return a bcrypt hash — aborting." >&2; exit 1 ;;
esac

say "AWS S3 (resume storage)"
note "The bucket and its existing files SURVIVED the old server — reuse the same bucket."
note "The IAM access keys did not, so mint a new key pair for the same bucket."
S3_REGION="$(ask_plain 'S3 region  [us-east-1]')"; S3_REGION="${S3_REGION:-us-east-1}"
S3_BUCKET="$(ask_plain 'S3 bucket  [dossier-resumes]')"; S3_BUCKET="${S3_BUCKET:-dossier-resumes}"
S3_ACCESS_KEY="$(ask_secret 'S3 access key id')"
S3_SECRET_KEY="$(ask_secret 'S3 secret access key')"

say "Email — Brevo SMTP (required before public signups)"
note "Brevo -> SMTP & API -> SMTP. Generate a NEW SMTP key; the old one is unrecoverable."
note "Leave the host blank to ship with email OFF (signups then need manual activation)."
MAIL_HOST="$(ask_plain 'SMTP host  [smtp-relay.brevo.com]')"; MAIL_HOST="${MAIL_HOST-}"
if [ -z "$MAIL_HOST" ]; then MAIL_HOST="smtp-relay.brevo.com"; fi
MAIL_PORT="$(ask_plain 'SMTP port  [587]')"; MAIL_PORT="${MAIL_PORT:-587}"
MAIL_USERNAME="$(ask_plain 'SMTP login (…@smtp-brevo.com)')"
MAIL_PASSWORD="$(ask_secret 'SMTP key')"
MAIL_FROM="$(ask_plain 'From address  [no-reply@kiwiply.com]')"; MAIL_FROM="${MAIL_FROM:-no-reply@kiwiply.com}"

say "Hostname + ACME"
SSLIP_HOST="$(ask_plain 'Base host  [kiwiply.com]')"; SSLIP_HOST="${SSLIP_HOST:-kiwiply.com}"
ACME_EMAIL="$(ask_plain "Let's Encrypt contact email")"

say "Server-side AI drafting (optional — press Enter to leave it OFF)"
note "Google AI Studio key. The old key is unrecoverable; mint a new one or skip."
DOSSIER_AI_API_KEY="$(ask_secret 'Gemini API key (blank = AI disabled)')"
if [ -n "$DOSSIER_AI_API_KEY" ]; then DOSSIER_AI_ENABLED=true; else DOSSIER_AI_ENABLED=false; fi

say "Writing $ENV_FILE"
umask 077
cat > "$ENV_FILE" <<ENVEOF
# Generated by scripts/migrate/05-bootstrap-env.sh on $(date -Is).
# Every '\$' is doubled to '\$\$' — Docker Compose interpolates '\$' in .env values.
# NEVER commit this file. Back it up somewhere you can actually read it back from
# (a password manager) — GitHub Actions secrets are write-only and cannot be recovered.

MYSQL_ROOT_PASSWORD=$(esc "$MYSQL_ROOT_PASSWORD")
JWT_BASE64_SECRET=$(esc "$JWT_BASE64_SECRET")

ADMIN_EMAIL=$(esc "$ADMIN_EMAIL")
ADMIN_LOGIN=$(esc "$ADMIN_LOGIN")
ADMIN_PASSWORD_HASH=$(esc "$ADMIN_PASSWORD_HASH")
ADMIN_MFA_ENABLED=false

S3_REGION=$(esc "$S3_REGION")
S3_BUCKET=$(esc "$S3_BUCKET")
S3_ACCESS_KEY=$(esc "$S3_ACCESS_KEY")
S3_SECRET_KEY=$(esc "$S3_SECRET_KEY")

SSLIP_HOST=$(esc "$SSLIP_HOST")
ACME_EMAIL=$(esc "$ACME_EMAIL")
CORS_ALLOWED_ORIGIN_PATTERNS=chrome-extension://*

MAIL_HOST=$(esc "$MAIL_HOST")
MAIL_PORT=$(esc "$MAIL_PORT")
MAIL_USERNAME=$(esc "$MAIL_USERNAME")
MAIL_PASSWORD=$(esc "$MAIL_PASSWORD")
MAIL_FROM=$(esc "$MAIL_FROM")

BREVO_API_KEY=
BREVO_LIST_ID=0
NEWSLETTER_POSTAL_ADDRESS=

DOSSIER_AI_ENABLED=$DOSSIER_AI_ENABLED
DOSSIER_AI_PROVIDER=gemini
DOSSIER_AI_MODEL=gemini-2.5-flash-lite
DOSSIER_AI_API_KEY=$(esc "$DOSSIER_AI_API_KEY")
DOSSIER_AI_FREE_MONTHLY_QUOTA=50
DOSSIER_AI_PARSE_MAX_OUTPUT_TOKENS=4000
ENVEOF
chmod 600 "$ENV_FILE"

say "Done — $ENV_FILE written (mode 600)"
note "Sanity check (shows only KEY names, no values):"
grep -oE '^[A-Z_]+=' "$ENV_FILE" | tr -d '=' | sed 's/^/      /'
echo
warn "Back this file up NOW, somewhere readable — a password manager, not GitHub secrets."
warn "Losing it again means reissuing every credential a second time."
echo
echo "Next:"
echo "  docker compose -f docker-compose.prod.yml pull"
echo "  docker compose -f docker-compose.prod.yml up -d"
echo "  docker compose -f docker-compose.prod.yml exec api printenv ADMIN_PASSWORD_HASH   # want a clean \$2y\$10\$… "
